agent_max_err_cnt: 5
execute_mode: rule
framework: tree_based_agentic_reasoning
key_file: keys_CHN.txt
llm_name: claude-sonnet-4-20250514
openai_base_url: xxx
max_explore_op: 50
max_explore_turn: 5
name: tree_based_agentic_reasoning_claude
