data_root: <local_data_root>/autoprep2
openai_base_url: xxx
nl2sql_data_root: xxx
git_local_repo: xxx/DeepPrep
agent_max_err_cnt: 3
benchmark: nl2sql-spider
cut_first_n_line: 2
cut_last_n_line: 10
cut_log: false
debug: true
execute_mode: rule
filecachedir: ./_tmp
gen_tbl_cut_col: 8
gen_tbl_cut_line: 5
ini_tbl_cut_col: 20
ini_tbl_cut_line: 20
line_limit: false
max_file_cnt: 30
max_input_limit: 35960
max_output_limit: 8012
diverse_input: false
parallel: true
print_key: false
record_log: false
temperature: 0.01
total_benchmarks:
- nl2sql-spider
- nl2sql-bird
- parrot
version: 1.0.0